services:
  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - kafka_data:/var/lib/kafka/data

  dagster:
    build: .
    command: dagster dev -h 0.0.0.0

    volumes:
      - .:/code
    ports:
      - "3000:3000"
    depends_on:
      - kafka
  consumer:
    build:
      dockerfile: consumer.dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000

    volumes:
      - ./consumer:/code
    ports:
      - "8000:8000"
    depends_on:
      - dagster


volumes:
  kafka_data: { }
