# Generated by Django 5.0.8 on 2024-08-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CountryStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("most_sold_product", models.CharField(max_length=255)),
                (
                    "most_sold_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("least_sold_product", models.CharField(max_length=255)),
                (
                    "least_sold_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total_sold", models.IntegerField()),
            ],
            options={
                "verbose_name": "Country Statistics",
                "verbose_name_plural": "Country Statistics",
            },
        ),
    ]
